import {
	trustFund,
	blickNews,
	desarrollos,
	elEditor,
	eugenie,
	flexy,
	elal,
	logoBlack,
	logoElemental,
	logoBlackHound,
	enoff,
	fundacion,
	merci,
	alohar,
	sacra,
	harrison,
	petricor,
} from '@/styles/assets/logos';

export const logos = [
	{
		link: 'https://trustfund.com.ar/',
		url: trustFund,
		alt: 'Logo trustFund',
		key: 14,
	},
	{
		link: 'https://blick.com.ar/',
		url: blickNews,
		alt: 'Logo Blick News',
		key: 15,
	},
	{
		link: 'https://desarrollosdelsud.com.ar/',
		url: desarrollos,
		alt: 'Logo Desarrollos Delsud',
		key: 16,
	},
	{
		link: 'https://eleditorplatense.com.ar/',
		url: elEditor,
		alt: 'Logo El editor Platense',
		key: 17,
	},
	{
		link: 'https://eugenie.com.ar/',
		url: eugenie,
		alt: 'Logo Eugenie',
		key: 18,
	},
	{
		link: 'https://blackwallet.com.ar/',
		url: logoBlack,
		alt: 'Logo Black wallet',
		key: 19,
	},
	{
		link: 'https://trustfund.com.ar/',
		url: trustFund,
		alt: 'Logo trustFund',
		key: 24,
	},
	{
		link: 'https://flexy.com.ar/',
		url: flexy,
		alt: 'Logo Flexy',
		key: 20,
	},
	{
		link: 'https://elal.com.ar/',
		url: elal,
		alt: 'Logo Elal',
		key: 21,
	},
	// {
	// 	link: 'https://grupodelsud.com/',
	// 	url: logoGrupo,
	// 	alt: 'Logo Grupo Delsud',
	// 	key: 27,
	// },
	{
		link: 'https://elementalconstructora.com.ar/',
		url: logoElemental,
		alt: 'Logo Elemental',
		key: 202,
	},
	{
		link: 'https://blackwallet.com.ar/',
		url: logoBlack,
		alt: 'Logo Black wallet',
		key: 203,
	},
	{
		link: 'https://blackhound.com.ar/',
		url: logoBlackHound,
		alt: 'Logo Black Hound',
		key: 206,
	},
	{
		link: 'https://enoff.com.ar/',
		url: enoff,
		alt: 'Logo En Off',
		key: 207,
	},
	{
		link: 'https://fundacion.grupodelsud.com/',
		url: fundacion,
		alt: 'Logo Fundacion',
		key: 208,
	},
	{
		link: 'https://merci.com.ar/',
		url: merci,
		alt: 'Logo Merci',
		key: 209,
	},
	{
		link: 'https://alohar.com.ar/',
		url: alohar,
		alt: 'Logo Alohar',
		key: 300,
	},
	{
		link: 'https://sacra.com.ar/',
		url: sacra,
		alt: 'Logo Sacra',
		key: 301,
	},
	{
		link: 'https://agenciaharrison.com.ar/',
		url: harrison,
		alt: 'Logo Harrison',
		key: 302,
	},
	{
		link: 'https://petricor.com.ar/',
		url: petricor,
		alt: 'Logo Petricor',
		key: 303,
	},
];
